### ISSUE TITLE
support to run a batch of transactions

### ISSUE THREAD

**Issue by l2fprod** [l2fprod/carpaccio-store#7] opened 2015-11-12 19:48 UTC
the idea is to simulate one month of activities.

given a list of transactions (product/qty/state), compute the money we could have made in theory (not tax, no discount), then call all pricing engines to get their actual results for this set of transactions.

**Comment by frawa** [comment] 2015-11-15 18:25
Somewhat duplicate of #15

**Closed** 2015-11-17 14:40 UTC
Labels: enhancement
